### PR TITLE
[#69] Add locallib require

### LINKED ISSUE #69: Failing unit tests
`lib.php` is missing a require for `locallib.php`, and so the publication class is missing during this unit test:

```
vendor/bin/phpunit --testsuite=core_calendar_testsuite --filter=test_delete_module_delete_events
Moodle 4.1.2+ (Build: 20230318), 314f2608a9351a23566ecc2b00882eaffb0767c0
Php: 8.0.24, mysqli: 8.0.31, OS: Linux 5.19.0-35-generic x86_64
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:23.952, Memory: 117.00 MB

There was 1 error:

1) core_calendar\container_test::test_delete_module_delete_events
Error: Class "publication" not found

/var/www/ec-41/mod/publication/lib.php:58
/var/www/ec-41/course/modlib.php:137
/var/www/ec-41/lib/testing/generator/module_generator.php:277
/var/www/ec-41/mod/publication/tests/generator/lib.php:80
/var/www/ec-41/calendar/tests/container_test.php:476
/var/www/ec-41/lib/phpunit/classes/advanced_testcase.php:80
```

### PR DESCRIPTION
**Pull request by matthewhilton**
Closes #69

### CODE REVIEW

**Comment by goggo24** [comment]
included in v4.2.0

**Review by lucaboesch — COMMENTED** [review]
That doesn't respect Moodle coding guidelines (spaces before and after the dot).

**Comment by goggo24** [comment]
Hmm, okay. I was told it was done - i will forward your feedback to our devteam.

**Comment by lucaboesch** [comment]
It was a misunderstanding from my side too, pardon me.
The Moodle coding guidelines do not strictly require a space before and a after a concatenating dot.

Sorry for the noise.

**Pull request closed without merging**
